# 语言
language: node_js

sudo: false

cache: 
  apt: true
  directories:
    - node_modules

# 安装node
node_js: stable

install:
  - npm install -D
  - cd ./test/smoke/template
  - npm install -D
  - cd ../../../

scripts:
  - npm test
